const express = require('express')
const { adminUserController } = require('../../controllers/admin/admin.controller')
const upload = require('../../middlewares/uploadFile')
const userMiddlewares = require('../../middlewares/user.middlewares.js')
const userRouter = express.Router()
userRouter.post('/list', adminUserController.getAllUser)
userRouter.get('/:id', adminUserController.getDetailUser)
userRouter.post('/create', [upload.single('avatar'),userMiddlewares.checkDuplicateEmail], adminUserController.createUser)
userRouter.post('/:id', [upload.single('avatar'),userMiddlewares.checkDuplicateEmail], adminUserController.updateUser)
module.exports = userRouter