const express = require('express')
const { adminUserController } = require('../../controllers/admin/admin.controller')
const upload = require('../../middlewares/uploadFile')
const userMiddlewares = require('../../middlewares/user.middlewares.js')
const authMiddlewares = require('../../middlewares/auth.middleware.js')
const userRouter = express.Router()
userRouter.post('/list',[authMiddlewares.verifyUser, authMiddlewares.authorizeRoles(['admin'])], adminUserController.getAllUser)
userRouter.get('/:id',[authMiddlewares.verifyUser, authMiddlewares.authorizeRoles(['admin'])], adminUserController.getDetailUser)
userRouter.post('/create', [authMiddlewares.verifyUser,authMiddlewares.authorizeRoles(['admin']), upload.single('avatar'),userMiddlewares.checkDuplicateEmail], adminUserController.createUser)
userRouter.post('/:id', [authMiddlewares.verifyUser,authMiddlewares.authorizeRoles(['admin']), upload.single('avatar'),userMiddlewares.checkDuplicateEmail], adminUserController.updateUser)
module.exports = userRouter